const express = require('express')
const controller = require('../controller/controller.js')
const router = express.Router()


router.get('/questions',controller.getQuestions)
router.get('/nonquestions',controller.getNonQuestions)
router.get('/ppdt',controller.getImage)
router.get('/tat',controller.getTatImages)
router.get('/wat',controller.getWatWords)
router.get('/gpe',controller.getGpeImage)
router.get('/srt',controller.getSrtQuestion)
router.get('/srt_resp',controller.getSrtResponses)
router.get('/ppdt_resp',controller.getPpdtResponses)
router.get('/gpe_resp',controller.getGpeResponses)
router.get('/wat_resp',controller.getWatResponses)
router.get('/tat_resp',controller.getTatResponses)
router.post('/questions',controller.insertQuestion)
router.post('/srt_feedback',controller.insertSrtFeedback)
router.post('/nonquestions',controller.insertNonQuestion)
router.post('/srt_resp',controller.insertSrtResponse)
router.post('/ppdt_resp',controller.insertPpdtResponse)
router.post('/tat_resp',controller.insertTatResponse)
router.post('/wat_resp',controller.insertWatResponse)
router.get('/personality_detection',controller.personalityDetection)
router.post('/alumni_ppdt_resp',controller.insertAlumniPpdtResponse)
router.post('/alumni_wat_resp',controller.insertAlumniWatResponse)
router.post('/alumni_tat_resp',controller.insertAlumniTatResponse)
router.post('/alumni_srt_resp',controller.insertAlumniSrtResponse)
router.post('/alumni_gpe_resp',controller.insertAlumniGpeResponse)
router.post('/gpe_resp',controller.insertGpeResponse)
router.route('/questions').get(controller.getQuestions).post(controller.insertQuestion).delete(controller.dropQuestion)
router.route('/nonquestions').get(controller.getNonQuestions).post(controller.insertNonQuestion).delete(controller.dropNonQuestion)
router.route('/result').get(controller.getResult).post(controller.storeResult).delete(controller.dropResult)
router.route('/nonresult').get(controller.getNonResult).post(controller.storeNonResult).delete(controller.dropNonResult)
module.exports = router;